version: '3.8'

networks:
  back-network:
    external: true
    name: back-network

services:
  mini-talk:
    image: mini-talk
    container_name: mini-talk
    build: .
    restart: always
    networks:
      - back-network
    environment:
      - MARIADB_URL=${MARIADB_URL}
      - MARIADB_USERNAME=${MARIADB_USERNAME}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - SECRET={$SECRET}
      - CLIENT_ID=${CLIENT_ID}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TZ=Asia/Seoul